"use client";
import { useState } from "react";
import { DetailPanel } from "./detail-panel";
import { ArenaAccounting } from "./arena-results";
import type { ArenaLane } from "./arena-results";
import type { SavedFixture } from "../examples/arena/history";
import type { RouterMeasurement } from "../examples/routing/live-client";
import type { RoutingReceipt } from "../src/routing";
const tabs = [{ id: "usage", label: "Usage", note: "Where the tokens went" }, { id: "trace", label: "Tool activity", note: "What reached the fixture host" }, { id: "decision", label: "Jev’s decision", note: "Evidence and selection policy" }, { id: "setup", label: "Test setup", note: "What stays the same" }] as const;
type Tab = (typeof tabs)[number]["id"];
export function ArenaInspector({ lanes, receipt, jevUsage, fixture, pending, exportRun, canExport }: {
  lanes: Partial<Record<"baseline" | "integrated", ArenaLane>>; receipt: RoutingReceipt | null; jevUsage: RouterMeasurement | null; fixture: SavedFixture; pending: boolean; exportRun: () => void; canExport: boolean;
}) {
  const [active, setActive] = useState<Tab>("usage");
  const current = tabs.find(tab => tab.id === active)!;
  function navigate(key: string) {
    const index = tabs.findIndex(tab => tab.id === active);
    const next = key === "ArrowRight" ? (index + 1) % tabs.length : key === "ArrowLeft" ? (index + tabs.length - 1) % tabs.length : key === "Home" ? 0 : key === "End" ? tabs.length - 1 : null;
    if (next === null) return false;
    setActive(tabs[next]!.id); document.getElementById(`inspect-tab-${tabs[next]!.id}`)?.focus(); return true;
  }
  return <div className="run-inspector"><DetailPanel title="Run details" trigger={<><span>Explore this run<small>Usage, tool activity and the decision behind the result</small></span><span className="inspector-summary">{pending ? "Updating live" : receipt ? "View details" : "See how it works"}</span></>}>
    <div className="inspector-body"><div className="inspector-tabs" role="tablist" aria-label="Run details">{tabs.map(tab => <button key={tab.id} id={`inspect-tab-${tab.id}`} role="tab" aria-selected={active === tab.id} aria-controls="inspect-panel" tabIndex={active === tab.id ? 0 : -1} onClick={() => setActive(tab.id)} onKeyDown={event => { if (navigate(event.key)) event.preventDefault(); }}>{tab.label}{tab.id === "trace" && Object.keys(lanes).length > 0 && <span title={Object.keys(lanes).length < 2 ? "Partial trace; one lane has not reported" : "Calls reported by both lanes"}>{Object.values(lanes).reduce((total, lane) => total + lane.result.toolCallCount, 0)}{Object.keys(lanes).length < 2 ? "+" : ""}</span>}</button>)}</div>
      <section id="inspect-panel" role="tabpanel" tabIndex={0} aria-labelledby={`inspect-tab-${active}`} className="inspector-panel"><div className="inspector-panel-heading"><div><p className="eyebrow">{current.label}</p><h2>{current.note}</h2></div></div>
        {active === "usage" && <ArenaAccounting lanes={lanes} jevUsage={jevUsage} />}
        {active === "trace" && <><p className="hint">Only calls received by the synthetic MCP host appear here. An agent’s written claim is not a tool event.</p><div className="trace-columns">{([['baseline', 'Without Jev'], ['integrated', 'With Jev']] as const).map(([id, label]) => <div className="trace-lane" key={id}><h3>{label}<span>{lanes[id] ? `${lanes[id].result.toolCallCount} ${lanes[id].result.toolCallCount === 1 ? "call" : "calls"} observed` : "Trace not available"}</span></h3>{lanes[id]?.result.toolCallCount ? <ol className="event-list">{lanes[id]!.result.toolCalls.map((call, index) => <li key={index}><span className="event-order">{index + 1}</span><div><strong>{call.tool}</strong><small>{call.status === "returned" ? "Fixture host returned a result" : "Fixture host rejected the call"}</small>{call.proposal && <details className="recorded-proposal"><summary>Inspect recorded proposal</summary><p className="hint">{call.proposal.path} · pending, never applied</p><p className="hint">{call.proposal.rationale}</p><pre>{call.proposal.patch}</pre></details>}</div><time dateTime={call.at}>{new Date(call.at).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit", second: "2-digit" })}</time></li>)}</ol> : <p className="inspector-empty">{lanes[id] ? "No fixture calls recorded." : pending ? "Waiting for this lane’s trace…" : "This lane did not return a trace. Its call count is unknown."}</p>}{lanes[id]?.result.traceTruncated && <p className="hint">Showing the first 100 calls. The count includes every observed call.</p>}</div>)}</div></>}
        {active === "decision" && (receipt ? <><div className="decision-summary"><span className="schema-chip">{receipt.selectedIds.join(" · ") || "No tool selected"}</span><p>Jev supplies evidence. The harness applies the selection policy; the host decides which fixture tools the CLI can use.</p></div><div className="decision-columns"><div><h3>Jev’s distribution<span>Relative evidence across the available choices</span></h3>{Object.entries(receipt.evidence?.probabilities ?? {}).map(([id, probability]) => <div className="probability-row" key={id}><div><span>{id}</span><strong>{Math.round(probability * 100)}%</strong></div><meter min={0} max={1} value={probability} aria-label={`${id} probability`} /></div>)}{!receipt.evidence && <p className="hint">No usable model evidence was returned.</p>}</div><div className="policy-card"><h3>How code selects tools</h3><p className="hint">{receipt.reason}</p><dl><div><dt>Maximum tools</dt><dd>{receipt.policy.topK}</dd></div><div><dt>Confidence floor</dt><dd>{receipt.policy.confidenceFloor}</dd></div><div><dt>Probability floor</dt><dd>{receipt.policy.probabilityFloor}</dd></div><div><dt>Per-tool cost limit</dt><dd>{receipt.policy.maxCostUnits} relative units</dd></div></dl></div></div><p className="hint">Probabilities and confidence are model statistics, not proof that a selection or answer is correct.</p><details className="raw-evidence"><summary>View raw routing receipt</summary><pre>{JSON.stringify(receipt, null, 2)}</pre></details></> : <p className="inspector-empty">Run a comparison to inspect Jev’s evidence and the resulting selection.</p>)}
        {active === "setup" && <><div className="setup-grid"><div><span>Held constant</span><h3>Same task and fixture</h3><p>Both lanes use the same installed Codex CLI, default model and read-only settings, with independent temporary workspaces.</p></div><div><span>The one change</span><h3>Tools exposed to the agent</h3><p>The baseline sees all fixture tools. The integrated lane sees the subset selected by the harness from Jev’s evidence.</p></div><div><span>Execution</span><h3>Two lanes, in parallel</h3><p>Jev routes first, then both agents start. Cache effects, shared resources and independent model trajectories can affect the result.</p></div></div><div className="fixture-preview"><div><span>Synthetic task</span><p>{fixture.task}</p></div>{Object.entries(fixture.files).map(([path, content]) => <details key={path}><summary>{path}<span className="summary-meta">View fixture source</span></summary><pre>{content}</pre></details>)}</div><p className="hint">The inspector tool is deterministic. Proposed patches are recorded, never applied. Answer quality is not scored automatically; one run is not a benchmark.</p></>}
      </section><div className="inspector-footer"><p>Keep the evidence for this run, including usage and both lanes.</p><button className="quiet" disabled={!canExport || pending} onClick={exportRun}>Download comparison</button></div>
    </div>
  </DetailPanel></div>;
}
