"use client";
import { useRef, useState } from "react";
import { integrationPrompt, INTEGRATION_REPO, type AdoptionMode } from "../examples/integration/prompt";
import { DetailPanel } from "./detail-panel";
export function ArenaIntegration({ onHistory, onCompare, pending }: { onHistory: () => void; onCompare: () => void; pending: boolean }) {
  const [mode, setMode] = useState<AdoptionMode>("shadow"), [notice, setNotice] = useState("");
  const text = useRef<HTMLTextAreaElement>(null), prompt = integrationPrompt(mode);
  async function copy() {
    try { await navigator.clipboard.writeText(prompt); setNotice("Integration prompt copied. Paste it into your coding agent in the host repository."); }
    catch { text.current?.focus(); text.current?.select(); setNotice("Clipboard access is unavailable. The prompt is selected; copy it manually or download it."); }
  }
  function download() {
    const url = URL.createObjectURL(new Blob([prompt + "\n"], { type: "text/markdown" }));
    const link = document.createElement("a"); link.href = url; link.download = `jev-integration-${mode}.md`; link.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
    setNotice("Integration prompt downloaded.");
  }
  return <div className="integration-workspace">
    {pending && <div className="integration-running" role="status">A comparison is running.<button className="quiet" onClick={onCompare}>View progress</button></div>}
    <section className="integration-handoff" aria-labelledby="integration-title">
      <div><p className="eyebrow">From demo to your codebase</p><h2 id="integration-title">Give your coding agent a clear brief.</h2><p>Keep your runtime. Add Jev where the host chooses which tools enter context, then measure the result.</p></div>
      <div className="integration-flow" aria-label="Your host supplies available tools; Jev supplies routing evidence; your host validates and dispatches"><span><small>Your host</small>Available tools</span><b aria-hidden="true">→</b><span><small>Jev</small>Routing evidence</span><b aria-hidden="true">→</b><span><small>Your host</small>Context &amp; dispatch</span></div>
      <fieldset className="adoption-modes"><legend>Choose an adoption stage</legend>{([['shadow', 'Observe first', 'Keep the full menu and record Jev’s selections. Recommended starting point.'], ['lean', 'Pilot selected tools', 'Expose Jev’s selected schemas after evaluating coverage and answer quality.']] as const).map(([id, label, description]) => <label key={id}><input type="radio" name="adoption-mode" value={id} checked={mode === id} onChange={() => { setMode(id); setNotice(""); }} /><span><strong>{label}</strong><small>{description}</small></span></label>)}</fieldset>
      <div className="integration-actions"><DetailPanel title="Your coding-agent integration prompt" trigger="Get integration prompt" triggerClass="primary"><p className="hint">Paste this in the repository that owns your coding harness. It asks the agent to inspect the host, pin the source, add the adapter, test it and document rollout. No saved keys, answers or notes are included.</p><label htmlFor="integration-prompt">{mode === "shadow" ? "Shadow adoption" : "Lean pilot"} prompt</label><textarea ref={text} id="integration-prompt" className="integration-prompt" readOnly value={prompt} spellCheck={false} /><div className="integration-actions"><button className="primary" onClick={() => void copy()}>Copy prompt</button><button className="quiet" onClick={download}>Download Markdown</button></div><p className="hint" role="status">{notice}</p></DetailPanel><a className="quiet integration-link" href={`${INTEGRATION_REPO}/blob/main/docs/integration.md`} target="_blank" rel="noopener noreferrer">Read the integration guide ↗</a></div>
      <p className="hint">This changes the brief only. It does not change Arena settings or start a provider request.</p>
    </section>
    <section className="integration-loop" aria-labelledby="improvement-title"><div className="integration-section-heading"><p className="eyebrow">Keep improving</p><h2 id="improvement-title">A repeatable loop, with evidence.</h2></div><ol>{[
      ["Freeze the baseline", "Keep the task, dataset and host/model settings fixed. Baseline makes no Jev call; shadow measures selection without reducing the menu."],
      ["Check the answers", "Inspect source evidence and required tool coverage. Record Meets task or Needs work for each lane; missing review remains unreviewed."],
      ["Compare repeated runs", "Count CLI and Jev input, output, cache reuse and time. Keep failures visible. Compare matching setups and check variation, not just the fastest run."],
      ["Change one thing", "Use a lesson to form a hypothesis. Version the descriptor, catalog or policy change; evaluate held-out tasks, then keep or revert it."],
    ].map(([title, copy]) => <li key={title}><h3>{title}</h3><p>{copy}</p></li>)}</ol><div className="integration-actions"><button className="quiet" onClick={onHistory}>Open local run history ↗</button><DetailPanel title="What to record in your harness" trigger="Measurement checklist"><p>Persist observations in the host’s own protected store. The Arena’s browser history is a demonstration cache, not a production database.</p><dl className="integration-records"><dt>Identity of the experiment</dt><dd>Run/trial ID, frozen task and dataset revision, baseline/shadow/lean mode, host commit, actual model, catalog, policy and prompt revisions.</dd><dt>Performance</dt><dd>CLI and Jev input/output tokens, cached input, attempt/retry count, routing and agent latency, concurrent wall time and reported monetary cost only when actually available. Missing values stay null.</dd><dt>Quality and coverage</dt><dd>Selected versus exposed tools, returned/rejected calls, routing outcome, failure/cancellation and independent test or human assessment with provenance.</dd><dt>Decision</dt><dd>Hypothesis, one changed variable, run evidence, quality tradeoffs and a keep/revert decision. Keep a baseline feature switch and a documented rollback.</dd></dl><p className="hint">Do not combine changed setups into one improvement claim. Human ratings are annotations, not automatic correctness scores. One run is an observation.</p></DetailPanel></div></section>
    <details className="integration-technical"><summary>Start with the working offline adapter<span className="summary-meta">Source-only · no API key</span></summary><p>The repository includes a typed example using the same public APIs your host will call.</p><pre><code>pnpm exec tsx examples/integration/host.ts</code></pre><p>Use <code>createCatalog</code> and <code>prepareToolContext</code>; inject your server-side <code>ToolRouter</code>. Keep permissions, argument validation, freshness checks and execution in your host. Cancellation discards the active context in both modes.</p><p><a href={`${INTEGRATION_REPO}/blob/main/examples/integration/host.ts`} target="_blank" rel="noopener noreferrer">Inspect the adapter example ↗</a> · <a href="https://docs.typesafe.ai/primitives/choice" target="_blank" rel="noopener noreferrer">Official Choice wire contract ↗</a></p><p className="hint">Independent community source, not a published SDK or production runtime. The proposal validator/runner extraction and context scoring are separate work; this guide uses the implemented routing boundary.</p></details>
  </div>;
}
