import type { runDemo } from "../examples/routing/demo-state";
type Result = Awaited<ReturnType<typeof runDemo>>;
export function Comparison({ result }: { result: Result | null }) {
  const m = result?.comparison.metrics, receipt = result?.comparison.receipt;
  const full = m?.fullContextEstimatedTokens ?? 0, lean = m?.leanTotalEstimatedInputTokens ?? null;
  const delta = lean === null ? null : full - lean;
  const takeaway = !receipt ? "Route a task to compare inputs." : receipt.outcome !== "selected" ? "No tool was selected. There is no equivalent completed task to compare." : delta === null ? "Routing usage is unknown. No savings comparison is available." : delta === 0 ? "Routing uses the same estimated input." : `Routing uses ${Math.abs(delta)} ${delta > 0 ? "fewer" : "more"} estimated input tokens (${Math.round(Math.abs(delta) / full * 100)}%).`;
  const rows = m ? [["Context tokens (estimate)", m.fullContextEstimatedTokens, m.leanContextEstimatedTokens], ["Router request bytes", 0, m.routerRequestBytes ?? "Unknown"], ["Total input tokens (estimate)", full, lean ?? "Unknown"], ["Router output tokens (estimate)", "Not called", m.routerResponseEstimatedTokens ?? "Unknown"]] : [];
  return <details id="comparison-panel"><summary>Does routing reduce the input?</summary><div className="disclosure-body"><p id="comparison-takeaway" className="comparison-takeaway">{takeaway}</p><p className="hint">Same task. Estimates include the extra request needed to choose a tool.</p><div className="comparison-options"><div className="comparison-option"><h3>Without routing</h3><strong>{m ? full.toLocaleString() : "—"}</strong><span className="unit">estimated input tokens</span><meter min={0} max={Math.max(full, lean ?? 0, 1)} value={full} aria-label="Without routing estimated input tokens" /><p>{result?.comparison.full.state.loadedIds.length ?? 0} available tool schemas + the task. No routing request.</p></div><div className="comparison-option routed"><h3>With routing</h3><strong id="routed-tokens">{m ? lean?.toLocaleString() ?? "Unknown" : "—"}</strong><span className="unit">estimated input tokens</span><meter min={0} max={Math.max(full, lean ?? 0, 1)} value={lean ?? 0} aria-label="With routing estimated input tokens" /><p id="routed-explanation">{m && lean !== null ? `${m.leanContextEstimatedTokens} for the task and ${result!.comparison.lean.state.loadedIds.length} selected ${result!.comparison.lean.state.loadedIds.length === 1 ? "schema" : "schemas"} + ${lean - m.leanContextEstimatedTokens} for routing.` : "Routing measurements are unavailable."}</p></div></div><p id="output-overhead" className="comparison-caveat">{m?.routerResponseEstimatedTokens == null ? "Routing output is unavailable; total usage cannot be compared." : `Routing also adds approximately ${m.routerResponseEstimatedTokens} output tokens, separate from the input above.`}</p><p className="hint">Text-size estimates, not measured usage or cost savings. Actual cost depends on provider pricing and caching. Nothing executes.</p><details className="technical-comparison"><summary>Show the calculation</summary><div className="metrics"><div><span>Task + all schemas</span><strong>{m?.fullContextBytes.toLocaleString() ?? "—"}</strong><small>UTF-8 bytes</small></div><div><span>Task + selected schemas</span><strong>{m?.leanContextBytes.toLocaleString() ?? "—"}</strong><small>UTF-8 bytes</small></div><div><span>Context reduction</span><strong>{m ? `${Math.round(m.contextReductionFraction * 100)}%` : "—"}</strong><small>excludes router overhead</small></div></div><table><caption>Same task and availability · both modes</caption><thead><tr><th scope="col">Measure</th><th scope="col">Without routing</th><th scope="col">With routing</th></tr></thead><tbody id="comparison">{rows.map(([label, a, b]) => <tr key={String(label)}><th scope="row">{label}</th><td>{a}</td><td>{b}</td></tr>)}</tbody></table><p className="hint">Token proxy: serialized UTF-8 bytes ÷ 4, rounded up. No task execution is measured.</p></details></div></details>;
}
