"use client";
import { useState } from "react";
import Link from "next/link";
import { DEMO_CATALOG } from "../examples/routing/scenarios";
export function ExampleLab() {
  const [active, setActive] = useState("schemas"), [selected, setSelected] = useState<string[]>(["read_file"]);
  const tools = DEMO_CATALOG.filter(tool => selected.includes(tool.id));
  const fullBytes = new TextEncoder().encode(JSON.stringify(DEMO_CATALOG.map(tool => tool.inputSchema))).length;
  const leanBytes = new TextEncoder().encode(JSON.stringify(tools.map(tool => tool.inputSchema))).length;
  return <main><div className="intro"><h1>Small experiments<span>.</span></h1><p>Explore one mechanism at a time, then compare a real agent in the arena.</p></div><section className="composer lab-card"><h2>Choose an experiment</h2><div className="experiment-list"><button className="quiet" aria-pressed={active === "schemas"} onClick={() => setActive("schemas")}>Schema explorer</button><button className="quiet" aria-pressed={active === "availability"} onClick={() => setActive("availability")}>Availability &amp; context</button><Link className="quiet" href="/arena">Codex agent arena ↗</Link></div><p className="hint">These local experiments make no model calls. The arena runs a real CLI agent against synthetic tools.</p></section><section className="result"><h2>{active === "schemas" ? "Only load what is needed" : "The host owns availability"}</h2><p className="result-reason">{active === "schemas" ? "Select tool descriptors and inspect their exact input schemas. A schema describes an action; it does not run it." : "Toggle tools to change the context surface. Routing cannot add a tool that the host did not make available."}</p><fieldset className="lab-tools"><legend>Tools in this context</legend>{DEMO_CATALOG.map(tool => <label key={tool.id}><input id={tool.id === "read_file" ? "task" : undefined} type="checkbox" checked={selected.includes(tool.id)} onChange={event => setSelected(event.target.checked ? [...selected, tool.id] : selected.filter(id => id !== tool.id))} />{tool.id}</label>)}</fieldset><p role="status" className="hint">{tools.length} schemas loaded · {leanBytes} schema bytes, compared with {fullBytes} for the full catalog. Excludes task and router overhead.</p></section><div className="inspection"><details><summary>Inspect the schema contract</summary><pre>{JSON.stringify(tools.map(tool => ({ id: tool.id, inputSchema: tool.inputSchema })), null, 2)}</pre></details><details><summary>What this does and does not show</summary><p className="hint">The catalog uses a small closed JSON Schema subset. The core rejects unsupported constraints rather than silently dropping them. Manual toggles demonstrate context composition, not model routing quality or provider savings. Use Routing room for model evidence and the arena for CLI runs.</p></details></div><footer>Independent community examples. No model calls on this page.</footer></main>;
}
