"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useEffect, useRef, useState } from "react";
import { readApiKey, saveApiKey, KEY_STORAGE } from "../examples/routing/api-key";
import { clearUsage, getUsage, summarizeUsage, type UsageEntry } from "../examples/routing/usage";
export function Header() {
  const pathname = usePathname();
  const keyDialog = useRef<HTMLDialogElement>(null), usageDialog = useRef<HTMLDialogElement>(null);
  const [saved, setSaved] = useState(false), [draft, setDraft] = useState(""), [error, setError] = useState("");
  const [entries, setEntries] = useState<UsageEntry[]>([]);
  const total = summarizeUsage(entries);
  useEffect(() => {
    const syncKey = () => setSaved(Boolean(readApiKey()));
    const syncUsage = () => setEntries([...getUsage()]);
    syncKey(); syncUsage();
    window.addEventListener("storage", syncKey); window.addEventListener("jev-key-change", syncKey); window.addEventListener("jev-usage-change", syncUsage);
    return () => { window.removeEventListener("storage", syncKey); window.removeEventListener("jev-key-change", syncKey); window.removeEventListener("jev-usage-change", syncUsage); };
  }, []);
  function save(value: string) {
    try { saveApiKey(value); setDraft(""); setError(""); setSaved(Boolean(value.trim())); window.dispatchEvent(new Event("jev-key-change")); return true; }
    catch { setError("Could not save. Check the key format and browser storage permissions."); return false; }
  }
  return <><header className="masthead"><div className="header-bar"><Link className="wordmark" href="/" aria-label="Jev Harness">jev<span> / harness</span></Link><div className="header-actions"><button className="quiet" id="usage-open" onClick={() => usageDialog.current?.showModal()}>Usage{total.requests ? ` · ${total.requests}` : ""}</button><button className="quiet" id="key-settings" onClick={() => keyDialog.current?.showModal()}>API key{saved ? " · saved" : ""}</button></div></div><nav className="page-tabs" aria-label="Demos">{[{ href: "/", label: "Routing room" }, { href: "/examples", label: "Examples" }, { href: "/arena", label: "Agent arena" }].map(tab => <Link key={tab.href} href={tab.href} aria-current={pathname === tab.href ? "page" : undefined}><span>{tab.label}</span></Link>)}</nav></header>
    <dialog ref={keyDialog} id="key-dialog" aria-labelledby="key-title" onClose={() => { setDraft(""); setError(""); }}><div className="dialog-heading"><h2 id="key-title">Your TypeSafe API key</h2><button className="quiet" aria-label="Close API key settings" onClick={() => keyDialog.current?.close()}>Close</button></div><p className="hint">{saved ? "A personal key is saved for this origin. It overrides the host's default." : "No personal key saved. Live requests use the host's default if configured."}</p><form onSubmit={event => { event.preventDefault(); if (draft.trim() && save(draft)) keyDialog.current?.close(); }}><label htmlFor="api-key">API key</label><input id="api-key" type="password" value={draft} onChange={event => setDraft(event.target.value)} autoComplete="off" autoCapitalize="none" spellCheck={false} maxLength={1024} required placeholder="Paste your TypeSafe API key" /><p className="hint">Saved unencrypted in this browser until removed. Masked on screen; sent only with live requests through this local host. The saved value is never displayed.</p><p role="alert" className="hint">{error}</p><div className="dialog-actions"><button className="primary" type="submit">Save key</button><button className="quiet" type="button" disabled={!saved} onClick={() => save("")}>Remove key</button></div></form></dialog>
    <dialog ref={usageDialog} id="usage-dialog" aria-labelledby="usage-title"><div className="dialog-heading"><h2 id="usage-title">Usage &amp; budget</h2><button className="quiet" aria-label="Close usage dashboard" onClick={() => usageDialog.current?.close()}>Close</button></div><p className="hint">This tab's latest 200 live Jev requests · survives refresh. Account-wide quotas and balances are unavailable.</p><div className="usage-totals"><div><span>Requests</span><strong id="usage-requests">{total.requests}</strong></div><div><span>Reported input</span><strong id="usage-input">{total.input.toLocaleString()}</strong></div><div><span>Reported output</span><strong id="usage-output">{total.output.toLocaleString()}</strong></div></div><p id="usage-unknown" className="hint">{total.unknown ? `${total.unknown} requests have incomplete usage. Totals include reported tokens only.` : total.requests ? "All listed requests have reported token usage." : "Run a task with Live Jev to see usage. Offline examples use no credits."}</p><div className="usage-price"><span>Reported-input price estimate</span><strong>${(total.input * 42 / 1_000_000_000).toFixed(8)}</strong><p className="hint">At <a href="https://typesafe.ai/" target="_blank" rel="noopener noreferrer">$42 per billion input tokens</a> (checked Sep 22, 2026). Excludes output, unknown usage and account-specific pricing. Not an invoice.</p></div><details><summary>Request history</summary><div className="table-scroll"><table><caption>Provider-reported tokens. Missing usage stays unknown.</caption><thead><tr>{["Time", "Status", "Input", "Output", "Duration"].map(label => <th scope="col" key={label}>{label}</th>)}</tr></thead><tbody>{entries.map((entry, index) => <tr key={index}><td>{new Date(entry.at).toLocaleTimeString()}</td><td>{entry.status} · {entry.keySource} key</td><td>{entry.input ?? "Unknown"}</td><td>{entry.output ?? "Unknown"}</td><td>{entry.latencyMs === null ? "Unknown" : `${(entry.latencyMs / 1000).toFixed(2)} s`}</td></tr>)}</tbody></table></div></details><details><summary>Request limits</summary><p className="hint">Local host: 30 starts/minute, 2 concurrent across keys and tabs. Local safeguards, not account quotas. Billing (402) and rate-limit (429) failures remain visible. No automatic retries.</p></details><button id="usage-clear" className="quiet" onClick={clearUsage}>Clear local usage history</button></dialog>
  </>;
}
