"use client";
import { useEffect, useRef, useState } from "react";
import { assembleContext, type ContextMode, type ContextState } from "../src/routing";
import { runDemo, type DemoInput } from "../examples/routing/demo-state";
import { DEMO_CATALOG, SCENARIOS } from "../examples/routing/scenarios";
import { liveRouter } from "../examples/routing/live-client";
import { Comparison } from "./comparison";
const initial: DemoInput = { intent: SCENARIOS[0]!.intent, availableIds: DEMO_CATALOG.map(t => t.id), topK: 1, maxCostUnits: 10, mode: "lean" };
type Result = Awaited<ReturnType<typeof runDemo>>;
export function RoutingRoom() {
  const [input, setInput] = useState(initial), [source, setSource] = useState<"mock" | "jev">("mock");
  const [result, setResult] = useState<Result | null>(null), [pending, setPending] = useState(false);
  const [status, setStatus] = useState("Ready to route."), [liveText, setLiveText] = useState("");
  const [history, setHistory] = useState<{ task: string; reason: string }[]>([]);
  const previous = useRef<ContextState>({ loadedIds: [] }), mode = useRef<ContextMode>("lean"), generation = useRef(0), controller = useRef<AbortController | null>(null);
  const sourceRef = useRef(source), settings = useRef<HTMLDetailsElement>(null);
  sourceRef.current = source;
  function invalidate() { controller.current?.abort(); generation.current++; setResult(null); setPending(false); setLiveText(""); setStatus("Task or policy changed. No current selection; route this task to refresh."); }
  async function run(next: DemoInput, live: boolean, addTurn: boolean) {
    invalidate();
    if (!next.intent.trim()) { setStatus("Enter a task to route."); return; }
    if (!Number.isFinite(next.maxCostUnits) || next.maxCostUnits < 0 || next.maxCostUnits > 100 || !Number.isInteger(next.maxCostUnits)) {
      setStatus("Enter a whole-number cost limit from 0 to 100.");
      if (settings.current) settings.current.open = true;
      const budget = document.getElementById("budget") as HTMLInputElement | null;
      budget?.reportValidity(); budget?.focus(); return;
    }
    const ticket = generation.current;
    const abort = new AbortController(); controller.current = abort;
    const router = live ? liveRouter(abort.signal) : undefined;
    setPending(true); setLiveText(live ? "Asking Jev to choose a tool…" : "");
    try {
      const computed = await runDemo(next, previous.current, router);
      if (ticket !== generation.current) return;
      const value = { ...computed, context: assembleContext(computed.comparison.receipt, mode.current, previous.current) };
      previous.current = value.context.state; setResult(value);
      const receipt = value.comparison.receipt;
      setStatus(`${receipt.outcome === "selected" ? `Selected ${receipt.selectedIds.join(", ")}` : receipt.outcome.replaceAll("_", " ")}. ${value.context.state.loadedIds.length} schemas loaded. Nothing executed.`);
      if (router) { const m = router.measurement; setLiveText(router.error ?? (m ? `Jev: ${m.inputTokens ?? "unknown"} input / ${m.outputTokens ?? "unknown"} output tokens reported · ${(m.latencyMs / 1000).toFixed(2)} s. Task execution is not measured.` : "No provider request was needed.")); }
      if (addTurn) setHistory(items => [...items, { task: next.intent, reason: receipt.reason }].slice(-4));
    } catch { if (ticket === generation.current) setStatus("Could not compare this task. Check the task and policy fields."); }
    finally { if (ticket === generation.current) setPending(false); }
  }
  useEffect(() => {
    void run(initial, false, true);
    const keyChanged = () => { if (sourceRef.current === "jev") invalidate(); };
    window.addEventListener("jev-key-change", keyChanged); window.addEventListener("storage", keyChanged);
    return () => { controller.current?.abort(); generation.current++; window.removeEventListener("jev-key-change", keyChanged); window.removeEventListener("storage", keyChanged); };
  }, []);
  function change(next: DemoInput, automatic = true) { setInput(next); invalidate(); if (automatic && source === "mock") void run(next, false, false); }
  function changeMode(next: ContextMode) { mode.current = next; setInput(value => ({ ...value, mode: next })); if (result) { const context = assembleContext(result.comparison.receipt, next, previous.current); previous.current = context.state; setResult({ ...result, context }); setStatus(`${result.comparison.receipt.outcome.replaceAll("_", " ")}. ${context.state.loadedIds.length} schemas loaded. Nothing executed.`); } }
  function download() { if (!result) return; const blob = new Blob([JSON.stringify({ generatedAt: new Date().toISOString(), source, ...result }, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = "routing-receipt.json"; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); }
  const receipt = result?.comparison.receipt, selected = receipt?.selectedIds ?? [], context = result?.context;
  const selection = !receipt ? pending ? "Choosing a tool…" : "Ready to route" : receipt.outcome === "selected" ? selected.join(" + ") : receipt.outcome === "needs_clarification" ? "Clarify the task" : receipt.outcome === "no_match" ? "No eligible tool" : "Evidence unavailable";
  const reason = !receipt ? "Run a task to produce fresh evidence." : receipt.outcome === "selected" ? `${result!.comparison.metrics.selectedEstimatedCostUnits} estimated cost ${result!.comparison.metrics.selectedEstimatedCostUnits === 1 ? "unit" : "units"} · lowest cost among eligible tools.` : source === "mock" && result?.comparison.scenarioId === "custom" ? "No scripted answer for this task. Choose a sample to see routing." : receipt.reason;
  return <main><div className="intro"><h1>Routing room<span>.</span></h1><p>Choose a task. See which tools enter context.</p></div>
    <section className="composer" aria-label="Task"><div className="source-row"><label htmlFor="source">Evidence source</label><select id="source" value={source} onChange={event => { const next = event.target.value as "mock" | "jev"; setSource(next); invalidate(); if (next === "mock") void run(input, false, false); }}><option value="mock">Offline examples</option><option value="jev">Live Jev</option></select></div><div className="scenario-row"><label htmlFor="scenario">Try a scenario</label><select id="scenario" value={SCENARIOS.find(s => s.intent === input.intent)?.id ?? "custom"} onChange={event => { const scenario = SCENARIOS.find(s => s.id === event.target.value); change({ ...input, intent: scenario?.intent ?? "" }, Boolean(scenario)); }} >{SCENARIOS.map(s => <option key={s.id} value={s.id}>{s.title}</option>)}<option value="custom">Custom task · live or clarification</option></select></div>
      <form id="task-form" onSubmit={event => { event.preventDefault(); if (!input.intent.trim()) return; void run(input, source === "jev", true); }}><label className="sr-only" htmlFor="task">Task message</label><textarea id="task" rows={3} value={input.intent} onChange={event => change({ ...input, intent: event.target.value }, false)} maxLength={16000} required aria-describedby="task-help" /><div className="compose-actions"><p id="task-help">{source === "jev" ? "Sends this task to TypeSafe when you run. Nothing executes." : "Scripted answers. Nothing executes."}</p><button className="primary" type="submit" id="route-button" disabled={pending}>{source === "jev" ? "Route with Jev" : "Route this task"}<span aria-hidden="true">↗</span></button></div></form>
      <details id="settings" ref={settings} className="settings"><summary><span>Tools &amp; policy</span><span id="flow-available" className="summary-meta">{input.availableIds.length} available</span></summary><div className="disclosure-body"><p className="hint">Change availability or limits. Live changes wait for an explicit run.</p><div id="tools">{DEMO_CATALOG.map(tool => <article className="tool" key={tool.id}><div className="tool-line"><input type="checkbox" id={`available-${tool.id}`} checked={input.availableIds.includes(tool.id)} onChange={event => change({ ...input, availableIds: event.target.checked ? [...input.availableIds, tool.id] : input.availableIds.filter(id => id !== tool.id) })} /><label htmlFor={`available-${tool.id}`}>{tool.id}</label></div><p className="hint">{tool.description}</p><div className="tool-meta"><span>{tool.kind} · {tool.estimatedCostUnits} cost units</span><span className="badge">{selected.includes(tool.id) ? "Selected" : input.availableIds.includes(tool.id) ? "Available" : "Unavailable"}</span></div></article>)}</div><fieldset className="controls"><legend className="sr-only">Selection policy</legend><label htmlFor="top-k">Maximum tools<select id="top-k" value={input.topK} onChange={event => change({ ...input, topK: Number(event.target.value) })}>{[1, 2, 3].map(n => <option key={n} value={n}>{n} tools</option>)}</select></label><label htmlFor="budget">Cost limit per tool<input id="budget" type="number" min={0} max={100} step={1} required value={Number.isNaN(input.maxCostUnits) ? "" : input.maxCostUnits} onChange={event => change({ ...input, maxCostUnits: event.target.value === "" ? NaN : Number(event.target.value) })} /></label></fieldset><p className="hint">Illustrative cost units. Confidence floor 0.70, probability floor 0.20, relevance window 0.10.</p></div></details>
    </section>
    <section className="result" aria-labelledby="flow-selection"><div className="result-heading"><p className="eyebrow">Routing selection</p><span className="evidence-label">{source === "jev" ? "Live Jev" : "Scripted evidence"}</span></div><h2 id="flow-selection">{selection}</h2><p id="flow-reason" className="result-reason">{reason}</p><p id="live-status" className="hint" role="status">{liveText}</p><div className="context-heading"><h3>Loaded context <span id="flow-loaded">{context ? `${context.state.loadedIds.length} ${context.state.loadedIds.length === 1 ? "schema" : "schemas"}` : "No current result"}</span></h3><fieldset className="mode"><legend className="sr-only">Context mode</legend>{([['lean', 'Lean'], ['full', 'Batteries included']] as const).map(([value, title]) => <label key={value}><input type="radio" name="mode" value={value} checked={input.mode === value} onChange={() => changeMode(value)} />{title}</label>)}</fieldset></div><div className="context-strip" id="context-strip">{context?.state.loadedIds.map(id => <span className="schema-chip" key={id}>{id}</span>)}{context && !context.state.loadedIds.length && <span className="empty-context">No schemas loaded</span>}</div><p className="hint">{input.mode === "lean" ? "Lean mode · selected tool schemas only." : "Batteries included · all available schemas."}</p></section>
    <div className="inspection"><details id="explanation"><summary>Why this selection</summary><div className="disclosure-body"><p id="decision" className="decision">{receipt?.reason ?? "Route a task for fresh evidence."}</p>{DEMO_CATALOG.map(tool => <div className="evidence-row" key={tool.id}><div className="evidence-heading"><span>{tool.id}</span><p className="tool-evidence">{receipt?.evidence?.probabilities[tool.id] === undefined ? "No usable evidence" : `${Math.round(receipt.evidence.probabilities[tool.id]! * 100)}% ${source === "jev" ? "provider" : "scripted"} probability`}</p></div><meter min={0} max={1} value={receipt?.evidence?.probabilities[tool.id] ?? 0} aria-label={`${tool.id} probability`} /></div>)}<p className="hint">Probabilities and confidence are evidence, not correctness or authorization.</p></div></details><Comparison result={result} /><details id="schema-panel"><summary>Inspect loaded schemas</summary><div className="disclosure-body"><p id="transition" className="hint">{context ? `Loaded: ${context.state.loadedIds.join(", ") || "none"}. Added: ${context.addedIds.join(", ") || "none"}. Evicted: ${context.evictedIds.join(", ") || "none"}.` : "No current result."}</p><pre>{context ? JSON.stringify(context.tools, null, 2) : ""}</pre></div></details><details id="receipt-panel"><summary>Inspect routing evidence and receipt</summary><div className="disclosure-body"><button className="quiet" id="download" onClick={download} disabled={!result}>Download receipt</button><pre id="receipt">{receipt ? JSON.stringify(receipt, null, 2) : ""}</pre></div></details><details id="history-panel"><summary>Recent tasks</summary><div className="chat" id="chat">{history.map((item, index) => <div className="message" key={index}><strong>You</strong><span>{item.task}</span><strong>Router</strong><span>{item.reason}</span></div>)}</div></details></div><p className="sr-only" id="status" role="status" aria-live="polite">{status}</p><footer>Independent community demo. Routing evidence is not authorization. Nothing executes.<br />Offline examples stay in this browser. Live Jev sends task text only when you run it.</footer>
  </main>;
}
